blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET


blogger_blog_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET


blogger_blog_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

# src/Blogger/BlogBundle/Resources/config/routing.yml
blogger_blog_blog_show:
    path:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+